#ifdef GUI_ENABLED

#include "scr_support.h"
#include "../gui_config.h"
#include "../gui_icons.h"
#include "../gui_navigation.h"
#include "../gui_theme.h"
#include <Arduino.h>

/* QR code bitmap — version 5, 37x37 modules, EC level M
   URL: https://github.com/Schmackos/ALX_Nova_Controller_2/blob/main/USER_MANUAL.md
   Generated by generate_qr.py — 1-bit row-major, 5 bytes/row */
#define QR_MODULES 37
#define QR_BYTES_PER_ROW 5
#define QR_SCALE 2          /* render each module as 2x2 pixels */
#define QR_PX (QR_MODULES * QR_SCALE)  /* 74 pixels */

static const uint8_t PROGMEM qr_bitmap[] = {
    0xFE, 0x01, 0xEC, 0x0B, 0xF8,
    0x82, 0x4C, 0xD0, 0x5A, 0x08,
    0xBA, 0xEE, 0x3E, 0x32, 0xE8,
    0xBA, 0xBD, 0xD3, 0xF2, 0xE8,
    0xBA, 0xF2, 0x2D, 0x4A, 0xE8,
    0x82, 0xC0, 0xAC, 0x12, 0x08,
    0xFE, 0xAA, 0xAA, 0xAB, 0xF8,
    0x00, 0xB1, 0x9E, 0xA8, 0x00,
    0xBE, 0x24, 0x36, 0xE3, 0xE0,
    0xF8, 0xF1, 0xC0, 0x49, 0x30,
    0x6E, 0x6E, 0x40, 0x7F, 0xD8,
    0x1C, 0xD6, 0x8F, 0x3D, 0x88,
    0x8E, 0xF6, 0xCB, 0xE6, 0xF8,
    0x1D, 0x04, 0xC9, 0x41, 0x00,
    0x43, 0x47, 0x42, 0x73, 0xD8,
    0x0C, 0x94, 0xE4, 0x01, 0x90,
    0xD6, 0xE6, 0x97, 0x56, 0xB0,
    0xF4, 0x41, 0x3A, 0x48, 0x30,
    0xEE, 0x39, 0xCA, 0xB8, 0xD8,
    0xC5, 0x25, 0x2F, 0xAE, 0x08,
    0x7B, 0x27, 0x5A, 0xC6, 0xE0,
    0xB4, 0x84, 0xAF, 0x4C, 0x40,
    0x9F, 0x49, 0xA6, 0xFD, 0xD8,
    0xC5, 0x56, 0x8E, 0xBB, 0x80,
    0xA7, 0x64, 0x37, 0x37, 0xA8,
    0xF8, 0xD7, 0x9C, 0x60, 0x00,
    0x93, 0xA8, 0x20, 0x77, 0x98,
    0xBD, 0xC0, 0x9E, 0x23, 0x90,
    0x8B, 0xA4, 0x10, 0xBF, 0xA0,
    0x00, 0xE0, 0xCD, 0x28, 0xD0,
    0xFE, 0x13, 0xCC, 0x2A, 0xB8,
    0x82, 0x82, 0x67, 0xA8, 0xC8,
    0xBA, 0xA1, 0x86, 0xBF, 0xB8,
    0xBA, 0x9B, 0x70, 0x36, 0xC8,
    0xBA, 0xF5, 0xC2, 0x58, 0x78,
    0x82, 0x7F, 0x0F, 0xBC, 0x88,
    0xFE, 0xE7, 0x16, 0xE4, 0x98
};

/* Back button callback */
static void on_back(lv_event_t *e) {
    (void)e;
    gui_nav_pop();
}

lv_obj_t *scr_support_create(void) {
    lv_obj_t *scr = lv_obj_create(NULL);
    lv_obj_add_style(scr, gui_style_screen(), LV_PART_MAIN);

    /* Title */
    lv_obj_t *title = lv_label_create(scr);
    lv_label_set_text(title, ICON_SUPPORT " Support");
    lv_obj_add_style(title, gui_style_title(), LV_PART_MAIN);
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 4);

    /* Scrollable container */
    lv_obj_t *cont = lv_obj_create(scr);
    lv_obj_set_size(cont, DISPLAY_HEIGHT, DISPLAY_WIDTH - 46);
    lv_obj_align(cont, LV_ALIGN_BOTTOM_MID, 0, -18);
    lv_obj_set_flex_flow(cont, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(cont, 4, LV_PART_MAIN);
    lv_obj_set_style_pad_all(cont, 4, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cont, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_width(cont, 0, LV_PART_MAIN);
    lv_obj_set_scrollbar_mode(cont, LV_SCROLLBAR_MODE_AUTO);

    /* Make scrollable for encoder */
    lv_group_add_obj(gui_nav_get_group(), cont);

    /* QR code rendered via lv_image with a pre-filled RGB565 buffer */
    static uint16_t qr_img_buf[QR_PX * QR_PX];
    static lv_image_dsc_t qr_img_dsc;

    /* Fill the pixel buffer from the 1-bit QR bitmap */
    const uint16_t black16 = 0x0000;
    const uint16_t white16 = 0xFFFF;
    for (int row = 0; row < QR_MODULES; row++) {
        for (int col = 0; col < QR_MODULES; col++) {
            int byte_idx = row * QR_BYTES_PER_ROW + (col / 8);
            int bit_idx = 7 - (col % 8);
            bool dark = (pgm_read_byte(&qr_bitmap[byte_idx]) >> bit_idx) & 1;
            uint16_t px = dark ? black16 : white16;
            for (int sy = 0; sy < QR_SCALE; sy++) {
                for (int sx = 0; sx < QR_SCALE; sx++) {
                    qr_img_buf[(row * QR_SCALE + sy) * QR_PX + (col * QR_SCALE + sx)] = px;
                }
            }
        }
    }

    /* Set up the LVGL image descriptor */
    qr_img_dsc.header.w = QR_PX;
    qr_img_dsc.header.h = QR_PX;
    qr_img_dsc.header.cf = LV_COLOR_FORMAT_RGB565;
    qr_img_dsc.header.stride = QR_PX * 2;
    qr_img_dsc.data_size = sizeof(qr_img_buf);
    qr_img_dsc.data = (const uint8_t *)qr_img_buf;

    lv_obj_t *qr_img = lv_image_create(cont);
    lv_image_set_src(qr_img, &qr_img_dsc);

    /* Description label */
    lv_obj_t *desc = lv_label_create(cont);
    lv_label_set_text(desc, "Scan the QR code to open\nthe user manual.");
    lv_obj_add_style(desc, gui_style_dim(), LV_PART_MAIN);
    lv_obj_set_width(desc, LV_PCT(100));
    lv_label_set_long_mode(desc, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(desc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

    /* Back button at bottom */
    lv_obj_t *back_btn = lv_obj_create(scr);
    lv_obj_set_size(back_btn, 60, 16);
    lv_obj_align(back_btn, LV_ALIGN_BOTTOM_MID, 0, -2);
    lv_obj_add_style(back_btn, gui_style_list_item(), LV_PART_MAIN);
    lv_obj_add_style(back_btn, gui_style_list_item_focused(), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_add_flag(back_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(back_btn, LV_OBJ_FLAG_SCROLLABLE);
    lv_group_add_obj(gui_nav_get_group(), back_btn);

    lv_obj_t *back_lbl = lv_label_create(back_btn);
    lv_label_set_text(back_lbl, ICON_BACK " Back");
    lv_obj_set_style_text_color(back_lbl, COLOR_TEXT_SEC, LV_PART_MAIN);
    lv_obj_add_style(back_lbl, gui_style_dim(), LV_PART_MAIN);
    lv_obj_center(back_lbl);
    lv_obj_add_event_cb(back_btn, on_back, LV_EVENT_CLICKED, NULL);

    return scr;
}

#endif /* GUI_ENABLED */
